# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 7170
  servlet:
    # 应用的访问路径
    context-path: /xy
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256



# 项目相关配置
xiaoyi:
  # 名称
  name: yixin-xiaoyi
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2023
  # 获取ip地址开关
  addressEnabled: false
  # 缓存懒加载
  cacheLazy: false
  # 临时目录
  tempDir: /home/xiaoyi/temp
  sm4Key: b76d21695adc2103
  signSecret: ^Jdbk^b!
  # 依赖资源路径
  libDir: /home/xiaoyi/lib
  # 项目线上域名
  link: https://prod-1g2hwkuj388457e3-1322104827.tcloudbaseapp.com/index


--- # 用户信息 配置
user:
  # 基础角色
  baseRoleId: 2
  # vip id
  vipRoleId: 4
  # 手机密钥
  phoneSecret: ENC(54c53eab73abd3dc4ad04bee3a5e7eace587a9310d69b54afae060bfcfbd52fb)
  # 用户缓存访问过期时间 单位：小时
  accessLogExpireTime: 24
  # 最大允许登录失败次数
  maxRetryCount: 5
  # 登录失败锁定时间 单位：分钟
  lockTime: 60

--- # 邀请模块
invite:
  # 用户需要邀请 10人 才能获取VIP
  inviteRecordsVip: 10
  # 获取的VIP天数
  inviteVipDays: 7

--- # 短信 配置
sms:
  accessKeyId: ENC(5d99d4d318d53b3b4d8791e764caf2a0c2fd09efd94666e760c43b6f551697e9)
  accessKeySecret: ENC(50fb139397ef20b73d729a69cf85d829c25723b75e20f7faac5bde6e35beca62)
  endpoint: dysmsapi.aliyuncs.com
  signName: 校易堂
  templateCode: SMS_464080847
  templateContent: 您的验证码为：%s，请勿泄露于他人！
  # 规定时间（一小时）内同一手机号最多调用短信次数 机制本身最大是5
  maxSmsCount: 3
  # 规定时间（一小时）内同一IP最多调用短信次数
  maxIpSmsCount: 5

--- # 礼包 配置
gift:
  url: https://pan.baidu.com/s/1V5uyivI_ne6SyNF7_ORoEA
  password: g8wq

feign:
  secretKey: ENC(798fe4986fb3470fb73597db86405828)
# 配置文件加密配置
jasypt:
  encryptor:
    # 指定为自定义的加密器
    bean: smEncryptHandler

--- # xxl-job 配置
xxl.job:
  # 执行器开关
  enabled: false
  # 调度中心地址：如调度中心集群部署存在多个地址则用逗号分隔。
  admin-addresses: http://127.0.0.1:7370/xxl-job-admin
  # 执行器通讯TOKEN：非空时启用
  access-token: xxl-job
  executor:
    # 执行器AppName：执行器心跳注册分组依据；为空则关闭自动注册
    appname:
    # 执行器端口号 执行器从9101开始往后写
    port: 9101
    # 执行器注册：默认IP:PORT
    address:
    # 执行器IP：默认自动获取IP
    ip:
    # 执行器运行日志文件存储磁盘路径
    logpath: ./logs/xxl-job
    # 执行器日志文件保存天数：大于3生效
    logretentiondays: 30

--- # 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
          # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能(对数据库有性能损耗 使用批量操作应考虑性能问题)
          url: jdbc:mysql://127.0.0.1:3306/yixin_xiaoyi?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
          username: yixin-xiaoyi
          password: ENC(ef82143905b358ae48e8b7f782ef4d9b4f215945cdae5eaeedcf114ce2cc717a)
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 10000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 60000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 900000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring:
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: ENC(819393c37cdb57b0837db2d19ea9a5d9)
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${xiaoyi.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

--- # Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期 设为3天，72小时 (必定过期) 单位: 秒
  timeout: 259200
  # token临时有效期 (指定时间无操作就过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # token前缀
  token-prefix: "Bearer"
  # jwt秘钥
  jwt-secret-key: wQ1UcLl7GXwPJRjZiZ77rX1G4w
--- # mail 邮件发送
mail:
  enabled: true
  host: smtp.qq.com
  port: 465
  # 是否需要用户名密码验证
  auth: true
  # 发送方，遵循RFC-822标准
  from: XXX
  # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
  user: XXX
  # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
  pass: XXX
  # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
  starttlsEnable: true
  # 使用SSL安全连接
  sslEnable: true
  # SMTP超时时长，单位毫秒，缺省值不超时
  timeout: 0
  # Socket连接超时值，单位毫秒，缺省值不超时
  connectionTimeout: 0

